version: '3.4'

networks:
  appnetwork:

services:
  app.db:
    image: mcr.microsoft.com/mssql/server
    ports: 
        - 1400:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password1!
    networks:
        - appnetwork
  incidentmanager.api:
    image: ${DOCKER_REGISTRY-}incidentmanagerapi
    build:
      context: .
      dockerfile: IncidentManager.Api/Dockerfile
    depends_on:
        - app.db
    networks:
        - appnetwork